FROM node:20-alpine
WORKDIR /usr/src/app

COPY package*.json ./
# Trỏ đường dẫn để lấy thư viện đã cài sẵn trên Windows ném vào container
COPY node_modules ./node_modules 

EXPOSE 3000
CMD ["npm", "run", "dev"]